version: "3"

services:
  pg:
    container_name: "pg-blog-db"
    image: postgres
    environment:
      POSTGRES_DB: pgdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"